### ISSUE TITLE
UTF8String not implemented?

### ISSUE THREAD

**Issue by m42i** [mitshell/libmich#10]
Am I doing something wrong or is the type UTF8String not implemented?

I'm using it like this example code:

```
from libmich.asn1.processor import *
TestUtf = inline(''' TestUtf ::= UTF8String ''')
TestUtf.set_val('example')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "libmich/asn1/ASN1.py", line 572, in set_val
    self._set_val_basic(val)
  File "libmich/asn1/ASN1.py", line 378, in _set_val_basic
    % (self.get_fullname(), self._type, val)))
libmich.asn1.utils.ASN1_OBJ: TestUTF: invalid UTF8String value: example.
```

I'm currently using `OCTET STRING` instead.

**Comment by mitshell** [comment]
The current string types supported by the compiler and BER encoder are:
(see libmich/asn1/utils.py)

    TYPE_BIT_STR        = 'BIT STRING'
    TYPE_OCTET_STR      = 'OCTET STRING'
    TYPE_IA5_STR        = 'IA5String'
    TYPE_PRINT_STR      = 'PrintableString'
    TYPE_NUM_STR        = 'NumericString'
    TYPE_VIS_STR        = 'VisibleString'

If I remember correctly, the PER codec supports only BIT STRING and OCTET STRING.
I never had to use it so I did not implemented it. I have no idea if UTF8 behaves exactly like OCTET STRING when encoding with BER, and I am prettu sure it does not behave like OCTET STRING with PER.

**Comment by ptorpman** [comment]
Hello!

Do you have any idea on when the UTF8String support might be finished?

A bientôt,
Peter

**Comment by mitshell** [comment]
Sorry, but I am not working on it at the moment, as I have no need for it.
Could you provide at least a specification extract that makes use of it,
and mutliple encoded / decoded messages according to it ?

2016-03-22 11:04 GMT+01:00 Peter R. Torpman <notifications@github.com>:

**Comment by ptorpman** [comment]
It seems most commercial softwares just treat UTF8String as an Octet string.... Could your software do the same until the correct implementation is in place? 
The reason I ask is since we have a lot of ASN.1 files that contain the UTF8String type...

The following repo has support for it.. in C.  https://github.com/vlm/asn1c

**Comment by mitshell** [comment]
I can confirm UTF8String does not behave like OCTET STRING, especially in PER. If you want something working better with it, look at pycrate (see README). I won't update libmich anymore.
