### ISSUE TITLE
global name 'plmn_id' is not defined

### ISSUE THREAD

**Issue by ravens** [mitshell/libmich#12]
Hi,

I am having this error message during the establishment of the S1Setup phase:

NameError: global name 'plmn_id' is not defined

Looks like it is related to the plmn_id variable which is not in the scope of the function create_enb_handler() in mme.py, so fixing it by passing the variable as a function argument. 

[mme-s1.txt](https://github.com/mitshell/libmich/files/167282/mme-s1.txt)

**Comment by mitshell** [comment]
thanks for reporting, commit cbfda3e80f34ed3e025c61374caf258535f64c7e should correct this.
