### ISSUE TITLE
Reading pcap Support ?

### ISSUE THREAD

**Issue by crudbug** [mitshell/libmich#3]
How can we read pcap files and decode EAP-AKA packets?

I am going through the source code to understand the architecture. I have been battling with scapy support for EAP-AKA.

Great little utility !

Thanks,
Alan

**Comment by mitshell** [comment]
There is no ready-to-use application to decode pcap file in the library.
There is however support for parsing pcap headers in libmich/formats/pcap.py, Ethernet / IP / UDP / TCP headers in libmich/formats/IP.py, IKEv2 headers in libmich/formats/IKEv2.py...

It should be easy to make an application that decodes pcap file and manipulates the decoded data.

Benoit

**Comment by crudbug** [comment]
Thanks mitshell for your work, I ended up using scapy for my problem..

**Comment by mitshell** [comment]
Hi, thanks for reporting the issue.
At the end, Scapy is much more full-featured than libmich. You can still
use the libmich EAP-AKA format on top of scapy. I guess 1 of the advantage
is the support of the crypto operations within libmich (including the
availability of the PRF1862 within the utils/ directory).


2015-06-08 19:39 GMT+02:00 Alan Kash <notifications@github.com>:
