### ISSUE TITLE
Handling of ASN.1 SET OF in PER encoder

### ISSUE THREAD

**Issue by pulkomandy** [mitshell/libmich#8]
The PER (unaligned) encoder will not encode the "SET OF" construct and raise an error. Since the encoding is exactly the same as SEQUENCE OF, would it be possible to add support for it?

**Comment by mitshell** [comment]
Hello,
commit https://github.com/mitshell/libmich/commit/dcc6b51895c8a26f028fb08a16adcd9c603498b1 should do the job. However, I did not test it. Could you point me to an ASN.1 specification which makes use of SET OF object together with PER ?

**Comment by pulkomandy** [comment]
Hello,
Unfortunately the specification I'm working with is not public. But, I can provide a reduced test case:

Definitions:
````
CCP DEFINITIONS AUTOMATIC TAGS ::=
BEGIN
	CCP-Groups ::= SET SIZE(0..8) OF INTEGER(0..131071)
END
````

Sample value:
````
groups CCP-Groups ::= { 1,2,3,4,5,6,7,8 }
````

Unaligned PER encoding (according to http://asn1-playground.oss.com/):
````
80000800 08000600 04000280 018000E0 0080
````

**Comment by mitshell** [comment]
OK, seems to work.
Here is my result:
````
>>> from libmich.asn1.processor import *; from libmich.asn1.PER import *; PER.VARIANT = 'U'
>>> ASN1.ASN1Obj.CODEC = PER
>>> c = inline('''CCP-Groups ::= SET SIZE(0..8) OF INTEGER(0..131071)''')
>>> c
<CCP-Groups (SET OF INTEGER type)>
>>> c.set_val( (1,2,3,4,5,6,7,8) )
>>> c.encode()
>>> hex(c)
'800008000800060004000280018000e0008'
````
I guess asn1-playground padded the last byte with zeros. The internal representation I have is the following and looks correct according to PER unaligned:
````
>>> for l in c._msg: l.C.Repr='bin'
>>> show(c)
### [CCP-Groups] ###
 ### [L] ###
  <[C] : 0b1000>
 ### [Layer] ###
  <[C] : 0b00000000000000001>
 ### [Layer] ###
  <[C] : 0b00000000000000010>
 ### [Layer] ###
  <[C] : 0b00000000000000011>
 ### [Layer] ###
  <[C] : 0b00000000000000100>
 ### [Layer] ###
  <[C] : 0b00000000000000101>
 ### [Layer] ###
  <[C] : 0b00000000000000110>
 ### [Layer] ###
  <[C] : 0b00000000000000111>
 ### [Layer] ###
  <[C] : 0b00000000000001000>
````
I'll close the issue. Thanks for reporting.
